config/routes.rb
Appexample::Application.routes.draw do
  
  get "usuarios/index"
  devise_for :usuarios
  resources :lojas

  root 'welcome#index'
  resources :clientes

end

app/models/autenticacao_database.rb
=begin
class AutenticacaoDatabase < ActiveRecord::Base
  self.abstract_class = true
  establish_connection "#{Rails.env}_qa"

end
=end

app/models/client.rb
class Client < ActiveRecord::Base

  establish_connection "#{Rails.env}_oabonlane"

  self.table_name = "clientes"

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	belongs_to :loja


   validates :loja, presence: true # Valida se o campo está preechido(não permite cadastrar campo em branco)
   validates :cpf, uniqueness: true #Valida se o parametro passado é único no banco(evita duplicidade) 
   validates :telefone, numericality: true #Valida se o parametro passado é um número


   has_attached_file :imagem, styles: { medium: "300x300>", thumb: "100x100>" }
   validates_attachment_content_type :imagem, content_type: /\Aimage\/.*\Z/


   

   def valida_campo_loja
 	 if self.loja_id.blank?
 		"-" * 15
 	 else
 	    Loja.find(self.loja_id).nome 	
     end
   end

   # def valida_campo_loja
   #   if self.loja_id.blank? != true 
   #      Loja.find(self.loja_id).nome
   #   else
   #      self.loja_id
   #   end
   # end


   def valida_campo_obs
   	 if self.obs.blank?
   	 	"-" * 15
   	 else
   	 	self.obs
   	 end
   	
   end


end

app/models/conta.rb
class Conta < ActiveRecord::Base

establish_connection "#{Rails.env}_oabonlane"
  belongs_to :usuario
  belongs_to :cliente
end

app/models/loja.rb
class Loja < ActiveRecord::Base
	has_many :clientes
end

app/models/parte.rb
class Parte < ActiveRecord::Base
  establish_connection "#{Rails.env}_qa"

   belongs_to :processo
end

app/models/processo.rb
class Processo < ActiveRecord::Base
  establish_connection "#{Rails.env}_qa"

   has_many :partes
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base

 enum role: [:normal_user, :admin]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
#encoding: utf-8
class ApplicationController < ActionController::Base
  include Pundit
  #protect_from_forgery

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

 private
 def user_not_authorized
	 flash[:notice] = "Você não tem permissão para fazer esta ação."
	 redirect_to(request.referrer || root_path)
	 end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]
  before_action :set_lojas, only: [:new, :update, :create, :edit]
  before_action :authenticate_usuario!


  # GET /clientes
  # GET /clientes.json
  def index
    if params[:search]
    @clientes = Cliente.where("nome like ?", "%#{params[:search]}%").paginate(:page => params[:page], :per_page => 10)
    else
    @clientes = Cliente.all.paginate(:page => params[:page], :per_page => 10)
  end
  #authorize @clientes
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cliente }
      else
        format.html { render action: 'new' }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :email, :cpf, :obs, :aniversario, :telefone, :loja_id, :imagem)
    end

    def set_lojas
      @lojas = Loja.all
    end
end

app/controllers/lojas_controller.rb
class LojasController < ApplicationController
  before_action :set_loja, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!

  # GET /lojas
  # GET /lojas.json
  def index
     if params[:search]
       @lojas = Loja.where("nome like ?", "%#{params[:search]}%")
     else
    @lojas = Loja.all
  end
  end

  # GET /lojas/1
  # GET /lojas/1.json
  def show
  end

  # GET /lojas/new
  def new
    @loja = Loja.new
  end

  # GET /lojas/1/edit
  def edit
  end

  # POST /lojas
  # POST /lojas.json
  def create
    @loja = Loja.new(loja_params)

    respond_to do |format|
      if @loja.save
        format.html { redirect_to @loja, notice: 'Loja was successfully created.' }
        format.json { render action: 'show', status: :created, location: @loja }
      else
        format.html { render action: 'new' }
        format.json { render json: @loja.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lojas/1
  # PATCH/PUT /lojas/1.json
  def update
    respond_to do |format|
      if @loja.update(loja_params)
        format.html { redirect_to @loja, notice: 'Loja was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @loja.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lojas/1
  # DELETE /lojas/1.json
  def destroy
    @loja.destroy
    respond_to do |format|
      format.html { redirect_to lojas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loja
      @loja = Loja.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loja_params
      params.require(:loja).permit(:nome, :cnpj, :enderereco, :beirro, :cidade, :estado, :telefone)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
	before_action :authenticate_usuario!

  def index
  	@usuarios = Usuario.all
  	#authorize @usuarios
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	
	def index
		@teste = "Ruby on Rails"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper

	def formata_NumeroTelefone(numero)
	   numero.gsub!(/\D/,"")
		  if numero.size > 8
		     num_formatado = "("
		     num_formatado << numero[0..1]
		     num_formatado << ") "
		     num_formatado << numero[2..5]
		     num_formatado << "-"
		     num_formatado << numero[6..9]
		     num_formatado
	      elsif numero.size == 8
	      	 num_formatado = "("
	      	 num_formatado << "xx"
	      	 num_formatado <<  ")"
	      	 num_formatado << " "
	      	 num_formatado << numero[0..3]
	      	 num_formatado << "-"
	      	 num_formatado << numero[4..7]
	      	 num_formatado
	      else
	      	numero
	      end
	end


	def formata_cpf(cpf)
		cpf.gsub!(/\D/,"")
		num_formatado = cpf[0..2]
		num_formatado << "."
		num_formatado << cpf[3..5]
		num_formatado << "."
		num_formatado << cpf[6..8]
		num_formatado << "-"
		num_formatado << cpf[9..10]
		num_formatado
	end

	def first_latter_uppercase(name)
	  new_name = name.split.map(& :capitalize)
	   new_name.each do |n|
	     if n == "Da" || n == "Das" || n == "Do" || n == "Dos" || n == "De"
		   n.downcase!	
	     end
			new_name
		 end
	end
	

end

app/helpers/lojas_helper.rb
module LojasHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clientes/_form.html.erb
<%= form_for @cliente, :html => { :class => "form-horizontal cliente",  :multipart => true } do |f| %>

  <% if @cliente.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @cliente.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

   <div class="form-group">
      <%= f.label :imagem, :class => 'control-label col-lg-2' %>
      <div class="col-lg-3">
      <%= f.file_field :imagem %>
      </div>
   </div>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-8">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>

  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-8">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>

  <div class="form-group">
    <%= f.label :cpf, :class => 'control-label col-lg-2' %>
    <div class="col-lg-8">
      <%= f.text_field :cpf, :class => 'form-control' %>
    </div>
    <%=f.error_span(:cpf) %>
  </div>

  <div class="form-group">
    <%= f.label :obs, :class => 'control-label col-lg-2' %>
    <div class="col-lg-8">
      <%= f.text_field :obs, :class => 'form-control' %>
    </div>
    <%=f.error_span(:obs) %>
  </div>

  <div class="form-group">
    <%= f.label :aniversario, :class => 'control-label col-lg-2' %>
    <div class="col-lg-8">
      <%= f.text_field :aniversario, :class => 'form-control' %>
    </div>
    <%=f.error_span(:aniversario) %>
  </div>

  <div class="form-group">
    <%= f.label :telefone, :class => 'control-label col-lg-2' %>
    <div class="col-lg-8">
      <%= f.text_field :telefone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:telefone) %>
  </div>

  <div class="form-group">
     <%=f.label :loja_id, :class => 'control-label col-lg-2' %>
     <div class="col-lg-8">  
      <%=f.collection_select(:loja_id, @lojas, :id, :nome, include_blank: true, :class => 'form-control')%>
      </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                clientes_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/clientes/edit.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/clientes/index.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h1>
    <span class="glyphicon glyphicon-user">
    </span><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
  </h1>
    <div class="search">
       <%= form_tag(clientes_path, :method => :get) do %>
          <%= text_field_tag 'search', nil, placeholder: 'Digite o nome para pesquisar' %>
            <%= submit_tag "search" %>
       <%end%>
    </div>
</div>

<table class="table table-striped">
  <thead>
     <tr>
        <!--<th><%#= model_class.human_attribute_name(:id) %></th>-->
        <th><%= model_class.human_attribute_name(:loja) %></th>
        <th><%= model_class.human_attribute_name(:nome) %></th>
        <th><%= model_class.human_attribute_name(:email) %></th>
        <th><%= model_class.human_attribute_name(:cpf) %></th>
        <th><%= model_class.human_attribute_name(:obs) %></th>
        <th><%= model_class.human_attribute_name(:aniversario) %></th>
        <th><%= model_class.human_attribute_name(:telefone) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
     </tr>
   </thead>
  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
     <!--<td><%#= link_to cliente.loja, cliente_path(cliente) %></td>-->

     <!--<#% if cliente.loja_id.blank? != true%>
          <td><%#= Loja.find(cliente.loja_id).nome %></td>
          <%#else%>
          <td><%=cliente.loja_id %></td>
          <%#end%>-->

        <td><%= cliente.valida_campo_loja %></td>

        <td><%=first_latter_uppercase(cliente.nome).join(' ')%></td>

        <td><%= cliente.email %></td>

        <%if cliente.cpf != "" or nil%>
        <td><%= formata_cpf(cliente.cpf) %></td>
        <%else%>
        <td><%= cliente.cpf %></td>
        <%end%>

        <td><%= cliente.valida_campo_obs %></td>

        <td><%= cliente.aniversario %></td>

        <%if cliente.telefone != "" or nil%>
        <td><%= formata_NumeroTelefone(cliente.telefone) %></td>
        <%else%>
        <td><%= cliente.telefone %></td>
        <%end%>

        <td>

          <%= link_to t('.show', :default => t("helpers.links.show")),
                      cliente_path(cliente), :class => 'btn btn-default btn-xs',  :class =>"label label-success"%>


          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cliente_path(cliente), :class => 'btn btn-default btn-xs' %>


          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cliente_path(cliente),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @posts %>
<br>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cliente_path,
            :class => 'btn btn-primary' %>

app/views/clientes/new.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'Novo %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/clientes/show.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
 <dt><strong><%= image_tag @cliente.imagem.url(:medium) %></strong></dt><br><br><br><br><br>
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @cliente.nome %></dd><br>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @cliente.email %></dd><br>
  <dt><strong><%= model_class.human_attribute_name(:cpf) %>:</strong></dt>
  <dd><%= @cliente.cpf %></dd><br>
  <dt><strong><%= model_class.human_attribute_name(:obs) %>:</strong></dt>
  <dd><%= @cliente.obs %></dd><br>
  <dt><strong><%= model_class.human_attribute_name(:aniversario) %>:</strong></dt>
  <dd><%= @cliente.aniversario %></dd><br>
  <dt><strong><%= model_class.human_attribute_name(:telefone) %>:</strong></dt>
  <dd><%= @cliente.telefone %></dd><br>
  <dt><strong><%= model_class.human_attribute_name(:loja) %>:</strong></dt>
  <%if @cliente.loja_id.blank? != true%>
  <dd><%= Loja.find(@cliente.loja_id).nome %></dd><br>
  <%else%>
  <dd><%= @cliente.loja_id %></dd><br>
  <%end%>

</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              clientes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cliente_path(@cliente), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cliente_path(@cliente),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Appexample" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- <a class="navbar-brand" href="lojas">Lojas</a>
        <a class="navbar-brand" href="clientes">Clientes</a> -->
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Início", root_path  %></li>
            <li><%= link_to "Usuarios", usuarios_index_path  %></li>
            <li><%= link_to "Lojas", lojas_path  %></li>
            <li><%= link_to "Clientes", clientes_path  %></li>
            

            <% if usuario_signed_in? %>
                <li><%= link_to "Sair", destroy_usuario_session_path, method: :delete  %></li>
                
            <% else %>
                <li><%= link_to "Logar", new_usuario_session_path  %></li>
                <li><%= link_to "Cadastrar um novo usuário", new_usuario_registration_path  %></li>
            <% end %>
          </ul>
           <% if usuario_signed_in? %>
           <h5 align="right"><b> Logado como: </b> <%= current_usuario.email%> </h5>
          <% end %> 
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
  </body>
</html>

app/views/lojas/_form.html.erb
<%= form_for @loja, :html => { :class => "form-horizontal loja" } do |f| %>

  <% if @loja.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@loja.errors.count, "error") %> prohibited this loja from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @loja.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>
  <div class="form-group">
    <%= f.label :cnpj, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :cnpj, :class => 'form-control' %>
    </div>
    <%=f.error_span(:cnpj) %>
  </div>
  <div class="form-group">
    <%= f.label :enderereco, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :enderereco, :class => 'form-control' %>
    </div>
    <%=f.error_span(:enderereco) %>
  </div>
  <div class="form-group">
    <%= f.label :beirro, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :beirro, :class => 'form-control' %>
    </div>
    <%=f.error_span(:beirro) %>
  </div>
  <div class="form-group">
    <%= f.label :cidade, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :cidade, :class => 'form-control' %>
    </div>
    <%=f.error_span(:cidade) %>
  </div>
  <div class="form-group">
    <%= f.label :estado, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :estado, :class => 'form-control' %>
    </div>
    <%=f.error_span(:estado) %>
  </div>
  <div class="form-group">
    <%= f.label :telefone, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :telefone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:telefone) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                lojas_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/lojas/edit.html.erb
<%- model_class = Loja -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lojas/index.html.erb
<%- model_class = Loja -%>
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
     <div class="search">
        <%= form_tag(lojas_path, :method => :get) do %>
           <%= text_field_tag 'search', nil, placeholder: 'Digite o nome para pesquisar' %>
           <%= submit_tag "search" %>
        <% end %>
        </div>
     </div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:nome) %></th>

      <th><%= model_class.human_attribute_name(:cnpj) %></th>
      <th><%= model_class.human_attribute_name(:enderereco) %></th>
      <th><%= model_class.human_attribute_name(:beirro) %></th>
      <th><%= model_class.human_attribute_name(:cidade) %></th>
      <th><%= model_class.human_attribute_name(:estado) %></th>
      <th><%= model_class.human_attribute_name(:telefone) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @lojas.each do |loja| %>
      <tr>
        <!-- <td><%#= link_to loja.id, loja_path(loja) %></td> -->
        <td><%= loja.nome %></td>
        <td><%= loja.cnpj %></td>
        <td><%= loja.enderereco %></td>
        <td><%= loja.beirro %></td>
        <td><%= loja.cidade %></td>
        <td><%= loja.estado %></td>
        <td><%= loja.telefone %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_loja_path(loja), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      loja_path(loja),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_loja_path,
            :class => 'btn btn-primary' %>

app/views/lojas/new.html.erb
<%- model_class = Loja -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/usuarios/index.html.erb
<%- model_class = Usuario -%>
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
     
<table class="table table-striped">
<thead>
    <tr>
      <th><%= model_class.human_attribute_name(:Login) %></th>
      <th><%= model_class.human_attribute_name(:Status) %></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usu| %>
      <tr>
        <td><%= usu.email %></td>
        <td><%= usu.role %></td>	       
      </tr>
    <% end %>
  </tbody>
</table>

app/views/welcome/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">.::Página inicial::.</h1><br>

<h5 align="center"><%= link_to "Cadastro de Clientes", clientes_path %></h5>